<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>12</LangVersion>
    <RootNamespace>Linearstar.Windows.RawInput</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Company>Linearstar</Company>
    <Description>A simple wrapper library for Raw Input.</Description>
    <Copyright>Copyright (c) 2019 mfakane</Copyright>
    <Authors>mfakane</Authors>
    <PackageLicenseExpression>Zlib</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/mfakane/rawinput-sharp</PackageProjectUrl>
    <PackageReleaseNotes>See the GitHub release notes for this version.</PackageReleaseNotes>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Version>0.2.0</Version>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
    <FileVersion>0.0.0.0</FileVersion>
    <PackageTags>Windows RawInput</PackageTags>
    <RepositoryUrl>https://github.com/mfakane/rawinput-sharp</RepositoryUrl>
    <Nullable>enable</Nullable>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\LICENSE.txt" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
